# Generated by Django 5.2 on 2026-03-25 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac_permission', '0015_auditlog_old_data_alter_auditlog_action_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('resource_type', models.CharField(help_text='如 pipeline:run, ansible:execution', max_length=100, verbose_name='资源类型')),
                ('environment', models.CharField(blank=True, help_text='如 PROD。如果为空，则表示拦截该资源下所有环境的操作。', max_length=100, null=True, verbose_name='生效环境')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approver_roles', models.ManyToManyField(blank=True, to='rbac_permission.role', verbose_name='指定的审批角色集合')),
            ],
            options={
                'verbose_name': '审批策略',
                'verbose_name_plural': '审批策略',
                'db_table': 'approval_policy',
            },
        ),
        migrations.CreateModel(
            name='ApprovalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='如: 生产环境_WebCore_主干发布', max_length=255, verbose_name='审批标题')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准 (后台发往引擎)'), ('rejected', '已驳回'), ('canceled', '发起人已撤销'), ('finished', '已执行 (放行成功)'), ('failed', '执行失败 (放行触发报错)')], default='pending', max_length=20, verbose_name='审批状态')),
                ('resource_type', models.CharField(help_text='标记要请求哪个底层模块', max_length=100, verbose_name='目标组件')),
                ('target_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='如果有特定的资源 ID，则记录')),
                ('payload', models.JSONField(verbose_name='原汁原味的 Request Body')),
                ('url_path', models.CharField(help_text='通过这个端点，系统可以代替发起人放行请求', max_length=255, verbose_name='拦截发往的 URL')),
                ('method', models.CharField(default='POST', max_length=10, verbose_name='HTTP动词')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='审批意见 / 为什么驳回')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='签批时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_approvals', to=settings.AUTH_USER_MODEL, verbose_name='实际签署人')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL, verbose_name='发起人工号')),
            ],
            options={
                'verbose_name': '审批工单记录',
                'verbose_name_plural': '审批工单记录',
                'db_table': 'approval_ticket',
                'ordering': ['-create_time'],
            },
        ),
    ]
