# Generated by Django 5.2 on 2026-05-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_center', '0002_approvalticket_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalpolicy',
            name='auto_pass_if_ai_verified',
            field=models.BooleanField(default=False, help_text='若自愈系统标明此操作安全，则自动放行不阻断', verbose_name='AI确信时自动放行'),
        ),
        migrations.AddField(
            model_name='approvalpolicy',
            name='match_rules',
            field=models.JSONField(blank=True, default=dict, help_text="例如 {'action': 'delete'}，空字典表示无条件拦截", verbose_name='载荷匹配规则'),
        ),
    ]
