# Generated by Django 5.2 on 2026-05-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_center', '0003_approvalpolicy_auto_pass_if_ai_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='代码中使用的唯一标识符，如 pipeline:run', max_length=100, unique=True, verbose_name='资源标识码')),
                ('name', models.CharField(max_length=100, verbose_name='资源展示名称')),
                ('icon', models.CharField(default='PartitionOutlined', max_length=50, verbose_name='AntD图标')),
                ('description', models.TextField(blank=True, null=True, verbose_name='详细描述')),
                ('is_active', models.BooleanField(default=True, help_text='禁用的资源将不会出现在策略配置的选项中', verbose_name='是否启用')),
                ('is_system', models.BooleanField(default=True, help_text='系统代码自动注册的资源标记为内置，不可删除', verbose_name='是否为系统内置')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发现时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '可拦截资源',
                'verbose_name_plural': '可拦截资源',
                'db_table': 'approval_resource',
            },
        ),
    ]
