# Generated by Django 5.2 on 2026-05-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_center', '0004_approvalresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalresource',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='详细描述(EN)'),
        ),
        migrations.AddField(
            model_name='approvalresource',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='资源展示名称(EN)'),
        ),
    ]
