# Generated by Django 5.2 on 2026-05-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_center', '0005_approvalresource_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalpolicy',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='策略名称(EN)'),
        ),
    ]
