# Generated by Django 5.2 on 2026-06-09 09:39

import django.db.models.deletion
from django.conf import settings
import django.core.validators
from django.db import migrations, models


def backfill_ticket_projects(apps, schema_editor):
    ApprovalTicket = apps.get_model('approval_center', 'ApprovalTicket')
    Project = apps.get_model('rbac_permission', 'Project')
    ProjectMember = apps.get_model('rbac_permission', 'ProjectMember')
    fallback_project = (
        Project.objects.filter(code='default').first()
        or Project.objects.first()
    )

    for ticket in ApprovalTicket.objects.filter(project__isnull=True).iterator():
        payload = ticket.payload if isinstance(ticket.payload, dict) else {}
        project_id = payload.get('project_id') or payload.get('project')
        project = None
        if project_id and str(project_id).isdigit():
            project = Project.objects.filter(id=project_id).first()
        if not project:
            membership = (
                ProjectMember.objects.filter(user_id=ticket.submitter_id)
                .select_related('project')
                .first()
            )
            project = membership.project if membership else fallback_project
        if project:
            ticket.project_id = project.id
            ticket.save(update_fields=['project'])


class Migration(migrations.Migration):

    dependencies = [
        ('approval_center', '0006_approvalpolicy_name_en'),
        ('rbac_permission', '0021_add_project_asset_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalpolicy',
            name='approval_timeout_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10080)], verbose_name='审批超时分钟数'),
        ),
        migrations.AddField(
            model_name='approvalticket',
            name='execution_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='底层执行响应快照'),
        ),
        migrations.AddField(
            model_name='approvalticket',
            name='execution_status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='底层响应状态码'),
        ),
        migrations.AddField(
            model_name='approvalticket',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批过期时间'),
        ),
        migrations.AddField(
            model_name='approvalticket',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='approval_center.approvalpolicy', verbose_name='命中的审批策略'),
        ),
        migrations.AddField(
            model_name='approvalticket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tickets', to='rbac_permission.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='approvalticket',
            name='request_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='请求幂等指纹'),
        ),
        migrations.RunPython(
            backfill_ticket_projects,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='approvalticket',
            constraint=models.UniqueConstraint(condition=models.Q(('request_fingerprint__gt', ''), ('status__in', ['pending', 'approved'])), fields=('request_fingerprint',), name='uniq_active_approval_fingerprint'),
        ),
    ]
