# Generated by Django 5.2 on 2026-03-17 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host_management', '0005_platform_access_key_platform_api_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('cmd', 'Ad-hoc 命令'), ('playbook', 'Playbook 剧本')], default='cmd', max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('unknown', '未知')], default='pending', max_length=20, verbose_name='状态')),
                ('content', models.TextField(help_text='如果是命令，则为shell指令；如果是剧本，则为playbook文件名或内容', verbose_name='命令或剧本内容')),
                ('extra_vars', models.JSONField(blank=True, default=dict, verbose_name='额外变量')),
                ('result_summary', models.JSONField(blank=True, help_text='记录执行成功、失败、跳过的主机数量', null=True, verbose_name='结果摘要')),
                ('resource_pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='host_management.resourcepool', verbose_name='目标资源池')),
            ],
            options={
                'verbose_name': 'Ansible 任务',
                'verbose_name_plural': 'Ansible 任务',
                'db_table': 'task_ansible',
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=128, null=True, verbose_name='目标主机')),
                ('output', models.TextField(verbose_name='执行输出')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='task_management.ansibletask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'db_table': 'task_log',
            },
        ),
    ]
