# Generated by Django 5.2 on 2026-03-17 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0006_sshcredential_host_credential_and_more'),
        ('task_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ansibletask',
            options={'verbose_name': 'Ansible 任务定义', 'verbose_name_plural': 'Ansible 任务定义'},
        ),
        migrations.RemoveField(
            model_name='ansibletask',
            name='result_summary',
        ),
        migrations.RemoveField(
            model_name='ansibletask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='task',
        ),
        migrations.AddField(
            model_name='ansibletask',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='ansibletask',
            name='content',
            field=models.TextField(help_text='指令或剧本内容', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='ansibletask',
            name='resource_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to='host_management.resourcepool', verbose_name='目标资源池'),
        ),
        migrations.AlterModelTable(
            name='ansibletask',
            table='task_ansible_template',
        ),
        migrations.CreateModel(
            name='AnsibleExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('unknown', '未知')], default='pending', max_length=20, verbose_name='执行状态')),
                ('result_summary', models.JSONField(blank=True, null=True, verbose_name='结果摘要')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='task_management.ansibletask', verbose_name='关联任务定义')),
            ],
            options={
                'verbose_name': 'Ansible 执行记录',
                'verbose_name_plural': 'Ansible 执行记录',
                'db_table': 'task_ansible_execution',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='tasklog',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='task_management.ansibleexecution', verbose_name='关联执行记录'),
        ),
    ]
