# Generated by Django 5.2 on 2026-03-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_alter_ansibletask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibleexecution',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Celery 任务 ID'),
        ),
        migrations.AddField(
            model_name='ansibletask',
            name='timeout',
            field=models.IntegerField(default=3600, verbose_name='超时时间(秒)'),
        ),
    ]
