# Generated by Django 5.2 on 2026-04-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_ansibleexecution_celery_task_id_ansibletask_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibleexecution',
            name='from_pipeline',
            field=models.BooleanField(default=False, verbose_name='来自流水线'),
        ),
    ]
