# Generated by Django 5.2 on 2026-04-24 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_add_from_pipeline_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, verbose_name='调度名称')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('schedule_type', models.CharField(choices=[('cron', '自定义 Cron'), ('interval', '固定间隔')], default='custom', max_length=20, verbose_name='调度类型')),
                ('cron_expression', models.CharField(blank=True, help_text='格式: 分 时 日 月 周，如 0 3 * * * 表示每天凌晨3点', max_length=64, null=True, verbose_name='Cron 表达式')),
                ('interval_value', models.IntegerField(default=1, verbose_name='间隔值')),
                ('interval_unit', models.CharField(choices=[('minutes', '分钟'), ('hours', '小时'), ('days', '天')], default='hours', max_length=10, verbose_name='间隔单位')),
                ('periodic_task_id', models.IntegerField(blank=True, null=True, verbose_name='Celery PeriodicTask ID')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='task_management.ansibletask', verbose_name='关联任务模板')),
            ],
            options={
                'verbose_name': 'Ansible 定时调度',
                'verbose_name_plural': 'Ansible 定时调度',
                'db_table': 'task_ansible_schedule',
                'ordering': ['-create_time'],
            },
        ),
    ]
