# Generated by Django 5.2 on 2026-05-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_add_ansible_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibleexecution',
            name='extra_vars_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='变量快照'),
        ),
        migrations.AddField(
            model_name='ansibletask',
            name='forks',
            field=models.IntegerField(default=5, help_text='Ansible forks 参数', verbose_name='并发数'),
        ),
    ]
