# Generated by Django 5.2 on 2026-05-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0006_ansibleexecution_extra_vars_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletask',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='内容哈希值'),
        ),
        migrations.AddField(
            model_name='ansibletask',
            name='create_type',
            field=models.CharField(choices=[('manual', '人工区'), ('ai', 'AI草稿区')], db_index=True, default='manual', max_length=20, verbose_name='创建类型'),
        ),
    ]
