# Generated by Django 5.2 on 2026-05-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0019_project_projectmember'),
        ('task_management', '0007_ansibletask_content_hash_ansibletask_create_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ansible_tasks', to='rbac_permission.project', verbose_name='所属项目'),
        ),
    ]
