# Celery Beat 部署
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansflow-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansflow-beat
  template:
    metadata:
      labels:
        app: ansflow-beat
    spec:
      containers:
      - name: beat
        image: docker.io/library/ansflow-worker:v1
        command: ["celery", "-A", "config", "beat", "-l", "info"]
        env:
        - name: DATABASE_URL
          value: "sqlite:////app/data/db.sqlite3"
        - name: CELERY_BROKER_URL
          value: "redis://ansflow-redis:6379/6"
        - name: SECRET_KEY
          value: "django-insecure-(&)t3&2pj^t-%kak)ym-+cqw3sw^+ce8ep@#43&i@h=i8p31@c"
        - name: ANSFLOW_LOG_DIR
          value: "/var/log/ansflow"
        - name: ANSFLOW_LOG_LEVEL
          value: "INFO"
        - name: ANSFLOW_LOG_JSON
          value: "true"
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
        - name: ansflow-logs
          mountPath: /var/log/ansflow
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: ansflow-data-pvc
      - name: ansflow-logs
        emptyDir: {}
