# Generated by Django 5.2 on 2026-05-13 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='主机名')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线')], default='offline', max_length=20, verbose_name='状态')),
                ('concurrency', models.IntegerField(default=0, verbose_name='并发数/池大小')),
                ('active_queues', models.JSONField(default=list, verbose_name='监听队列')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
            ],
            options={
                'verbose_name': 'Worker 节点',
                'verbose_name_plural': 'Worker 节点',
                'db_table': 'pulse_worker_node',
            },
        ),
        migrations.CreateModel(
            name='TaskPulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('task_id', models.CharField(max_length=128, unique=True, verbose_name='任务 ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='任务名称')),
                ('args', models.TextField(blank=True, null=True, verbose_name='位置参数')),
                ('kwargs', models.TextField(blank=True, null=True, verbose_name='关键字参数')),
                ('state', models.CharField(choices=[('PENDING', '等待中'), ('RECEIVED', '已接收'), ('STARTED', '运行中'), ('SUCCESS', '成功'), ('FAILURE', '失败'), ('REVOKED', '已撤销'), ('RETRY', '重试中')], default='PENDING', max_length=20, verbose_name='任务状态')),
                ('runtime', models.FloatField(blank=True, null=True, verbose_name='运行耗时(秒)')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='错误堆栈')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='task_pulse.workernode', verbose_name='执行节点')),
            ],
            options={
                'verbose_name': '任务脉搏',
                'verbose_name_plural': '任务脉搏',
                'db_table': 'pulse_task_track',
                'ordering': ['-create_time'],
            },
        ),
    ]
