# Generated by Django 5.2 on 2026-05-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pulse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpulse',
            name='exchange',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='交换机'),
        ),
        migrations.AddField(
            model_name='taskpulse',
            name='parent_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='父任务 ID'),
        ),
        migrations.AddField(
            model_name='taskpulse',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='执行结果'),
        ),
        migrations.AddField(
            model_name='taskpulse',
            name='routing_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='路由键'),
        ),
        migrations.AddField(
            model_name='workernode',
            name='load_avg',
            field=models.JSONField(default=list, verbose_name='负载平均值'),
        ),
        migrations.AddField(
            model_name='workernode',
            name='pool_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='池类型'),
        ),
        migrations.AddField(
            model_name='workernode',
            name='processed_count',
            field=models.IntegerField(default=0, verbose_name='已处理任务数'),
        ),
        migrations.AddField(
            model_name='workernode',
            name='sw_sys',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='系统平台'),
        ),
        migrations.AddField(
            model_name='workernode',
            name='sw_ver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='软件版本'),
        ),
    ]
