# Generated by Codex on 2026-05-29

from django.db import migrations, models


def backfill_worker_hostname(apps, schema_editor):
    TaskPulse = apps.get_model('task_pulse', 'TaskPulse')
    for pulse in TaskPulse.objects.select_related('worker').filter(worker__isnull=False, worker_hostname__isnull=True):
        pulse.worker_hostname = pulse.worker.hostname
        pulse.save(update_fields=['worker_hostname'])


class Migration(migrations.Migration):

    dependencies = [
        ('task_pulse', '0002_taskpulse_exchange_taskpulse_parent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpulse',
            name='worker_hostname',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='执行节点名称'),
        ),
        migrations.RunPython(backfill_worker_hostname, migrations.RunPython.noop),
    ]
