# Generated by Django 5.2 on 2026-03-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(help_text='如: Harbor-ProjA', max_length=100, unique=True, verbose_name='仓库名称')),
                ('url', models.CharField(help_text='如: https://hub.docker.com 或 harbor.domain.com', max_length=255, verbose_name='仓库地址')),
                ('namespace', models.CharField(blank=True, help_text='如: library (可选)', max_length=100, null=True, verbose_name='默认命名空间')),
                ('username', models.CharField(max_length=100, verbose_name='认证用户名')),
                ('password', models.CharField(help_text='存储明文或简单加密供背后构建使用', max_length=255, verbose_name='认证密码/Token')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述信息')),
            ],
            options={
                'verbose_name': '镜像仓库',
                'verbose_name_plural': '镜像仓库',
                'db_table': 'pipeline_image_registry',
                'ordering': ['-create_time'],
            },
        ),
    ]
