# Generated by Django 5.2 on 2026-03-23 05:06

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageregistry',
            name='password',
            field=utils.fields.EncryptedCharField(max_length=255, verbose_name='认证密码/Token'),
        ),
    ]
