# Generated by Django 5.2 on 2026-04-21 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0009_pipeline_version'),
        ('registry_management', '0002_alter_imageregistry_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(help_text='如: backend-api, frontend-web', max_length=255, verbose_name='产物名称')),
                ('type', models.CharField(choices=[('docker_image', 'Docker 镜像'), ('jar', 'JAR 包'), ('binary', '二进制文件'), ('helm_chart', 'Helm Chart'), ('other', '其他')], default='docker_image', max_length=20, verbose_name='产物类型')),
                ('repository', models.CharField(blank=True, help_text='如: library/backend-api', max_length=255, null=True, verbose_name='仓库路径')),
                ('latest_tag', models.CharField(blank=True, max_length=128, null=True, verbose_name='最新版本')),
                ('latest_digest', models.CharField(blank=True, max_length=128, null=True, verbose_name='最新 Digest (SHA256)')),
                ('latest_size', models.BigIntegerField(default=0, verbose_name='最新大小 (bytes)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='pipeline_management.pipeline', verbose_name='关联流水线')),
                ('registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='registry_management.imageregistry', verbose_name='所属仓库')),
            ],
            options={
                'verbose_name': '流水线产物',
                'verbose_name_plural': '流水线产物',
                'db_table': 'pipeline_artifact',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('tag', models.CharField(help_text='如: v1.0.0, latest, 20240101', max_length=128, verbose_name='版本标签')),
                ('digest', models.CharField(blank=True, max_length=128, null=True, verbose_name='Digest (SHA256)')),
                ('size', models.BigIntegerField(default=0, verbose_name='大小 (bytes)')),
                ('image_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='完整镜像地址')),
                ('build_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='构建人')),
                ('commit_sha', models.CharField(blank=True, max_length=64, null=True, verbose_name='代码 Commit SHA')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='registry_management.artifact', verbose_name='所属产物')),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_versions', to='pipeline_management.pipelinerun', verbose_name='关联流水线运行')),
            ],
            options={
                'verbose_name': '产物版本',
                'verbose_name_plural': '产物版本',
                'db_table': 'pipeline_artifact_version',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['name'], name='pipeline_ar_name_f124d4_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['type'], name='pipeline_ar_type_6c9a55_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactversion',
            index=models.Index(fields=['artifact', 'tag'], name='pipeline_ar_artifac_e3a944_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactversion',
            index=models.Index(fields=['digest'], name='pipeline_ar_digest_864b3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artifactversion',
            unique_together={('artifact', 'tag')},
        ),
    ]
