# Generated by Django 5.2 on 2026-04-21 08:11

import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0009_pipeline_version'),
        ('registry_management', '0003_artifact_artifactversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactoryInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(help_text='如: JFrog-Production', max_length=100, unique=True, verbose_name='实例名称')),
                ('url', models.CharField(help_text='如: https://jfrog.company.com/artifactory', max_length=255, verbose_name='Artifactory 地址')),
                ('username', models.CharField(help_text='通常为 admin 或专用服务账号', max_length=100, verbose_name='认证用户名')),
                ('api_key', utils.fields.EncryptedCharField(help_text='Artifactory API Key（优先使用）', max_length=512, verbose_name='API Key')),
                ('password', utils.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='密码（备用）')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
            ],
            options={
                'verbose_name': 'Artifactory 实例',
                'verbose_name_plural': 'Artifactory 实例',
                'db_table': 'registry_artifactory_instance',
                'ordering': ['-create_time'],
            },
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='registry',
        ),
        migrations.AddField(
            model_name='artifact',
            name='image_registry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='registry_management.imageregistry', verbose_name='镜像仓库'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='source_type',
            field=models.CharField(choices=[('docker', 'Docker 镜像 / Harbor'), ('artifactory', 'Artifactory 制品库')], default='docker', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='type',
            field=models.CharField(choices=[('docker_image', 'Docker 镜像'), ('jar', 'JAR 包'), ('npm_package', 'npm 包'), ('binary', '二进制文件'), ('helm_chart', 'Helm Chart'), ('pypi_package', 'Python 包'), ('other', '其他')], default='docker_image', max_length=20, verbose_name='产物类型'),
        ),
        migrations.CreateModel(
            name='ArtifactoryRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('repo_key', models.CharField(help_text='如: libs-release, npm-local, company-docker', max_length=255, verbose_name='仓库 Key')),
                ('repo_type', models.CharField(choices=[('maven', 'Maven'), ('npm', 'npm'), ('generic', 'Generic'), ('helm', 'Helm'), ('docker', 'Docker'), ('pypi', 'PyPI'), ('go', 'Go'), ('other', '其他')], default='generic', max_length=20, verbose_name='仓库类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='registry_management.artifactoryinstance', verbose_name='所属实例')),
            ],
            options={
                'verbose_name': 'Artifactory 仓库',
                'verbose_name_plural': 'Artifactory 仓库',
                'db_table': 'registry_artifactory_repository',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifactory_repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='registry_management.artifactoryrepository', verbose_name='Artifactory 仓库'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['source_type'], name='pipeline_ar_source__821b16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artifactoryrepository',
            unique_together={('instance', 'repo_key')},
        ),
    ]
