# Generated by Django 5.2 on 2026-03-25 04:42

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(help_text='如: PROD-SSH-KEY', max_length=100, unique=True, verbose_name='凭据标识')),
                ('type', models.CharField(choices=[('ssh_key', 'SSH 私钥'), ('login_pass', '用户名密码对'), ('token', 'API Token / Secret'), ('file', '敏感文件内容 (如证书)')], max_length=20, verbose_name='凭据类型')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联用户名')),
                ('secret_value', utils.fields.EncryptedCharField(help_text='SSH密钥、密码、Token等', max_length=4096, verbose_name='加密原始值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='用途备注')),
            ],
            options={
                'verbose_name': '全局凭据',
                'verbose_name_plural': '全局凭据',
                'db_table': 'sys_credential_vault',
                'ordering': ['-create_time'],
            },
        ),
    ]
