# Generated by Django 5.2 on 2026-05-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_management', '0001_initial'),
        ('rbac_permission', '0019_project_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='rbac_permission.project', verbose_name='所属项目'),
        ),
    ]
