# Generated by Django 5.2 on 2026-03-18 03:44

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='K8sCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='集群名称')),
                ('auth_type', models.CharField(choices=[('kubeconfig', 'Kubeconfig 文件'), ('token', 'Token 认证')], default='kubeconfig', max_length=20)),
                ('kubeconfig_content', utils.fields.EncryptedTextField(blank=True, null=True, verbose_name='Kubeconfig 内容')),
                ('api_server', models.URLField(blank=True, null=True, verbose_name='API Server 地址')),
                ('token', utils.fields.EncryptedTextField(blank=True, null=True, verbose_name='认证 Token')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='连接状态')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='K8s 版本')),
            ],
            options={
                'verbose_name': 'K8s 集群',
                'db_table': 'k8s_clusters',
            },
        ),
    ]
