# Generated by Django 5.2 on 2026-05-06 04:27

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelmRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='仓库名称')),
                ('url', models.URLField(verbose_name='仓库 URL')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名')),
                ('password', utils.fields.EncryptedTextField(blank=True, null=True, verbose_name='密码/Token')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Helm 仓库',
                'db_table': 'helm_repositories',
            },
        ),
    ]
