# Generated by Django 5.2 on 2026-05-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_management', '0002_helmrepository'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8scluster',
            name='cpu_capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='总CPU容量'),
        ),
        migrations.AddField(
            model_name='k8scluster',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='k8scluster',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间'),
        ),
        migrations.AddField(
            model_name='k8scluster',
            name='memory_capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='总内存容量'),
        ),
        migrations.AddField(
            model_name='k8scluster',
            name='node_count',
            field=models.IntegerField(default=0, verbose_name='节点总数'),
        ),
        migrations.AddField(
            model_name='k8scluster',
            name='ready_node_count',
            field=models.IntegerField(default=0, verbose_name='就绪节点数'),
        ),
    ]
