# Generated by Django 5.2 on 2026-05-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_management', '0003_k8scluster_cpu_capacity_k8scluster_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='应用名称')),
                ('namespace', models.CharField(default='default', max_length=63, verbose_name='目标命名空间')),
                ('git_repo', models.CharField(max_length=512, verbose_name='Git 仓库地址')),
                ('git_branch', models.CharField(default='main', max_length=128, verbose_name='Git 分支')),
                ('path', models.CharField(default='.', max_length=255, verbose_name='Helm Chart 路径')),
                ('auto_sync', models.BooleanField(default=False, verbose_name='是否自动同步')),
                ('sync_status', models.CharField(choices=[('Synced', '已同步'), ('OutOfSync', '失步'), ('Unknown', '未知'), ('Error', '同步错误')], default='Unknown', max_length=20, verbose_name='同步状态')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
                ('last_sync_revision', models.CharField(blank=True, max_length=128, null=True, verbose_name='最近同步的版本(Commit ID)')),
                ('diff_details', models.JSONField(blank=True, default=dict, verbose_name='漂移详情')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='k8s_management.k8scluster', verbose_name='目标集群')),
            ],
            options={
                'verbose_name': 'K8s 应用 (GitOps)',
                'verbose_name_plural': 'K8s 应用 (GitOps)',
                'db_table': 'k8s_applications',
            },
        ),
    ]
