# Generated by Django 5.2 on 2026-05-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_management', '0004_k8sapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8sapplication',
            name='sync_status',
            field=models.CharField(choices=[('Synced', '已同步'), ('OutOfSync', '失步'), ('Syncing', '同步中'), ('Unknown', '未知'), ('Error', '同步错误')], default='Unknown', max_length=20, verbose_name='同步状态'),
        ),
    ]
