# Generated by Django 5.2 on 2026-05-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s_management', '0005_alter_k8sapplication_sync_status'),
        ('rbac_permission', '0019_project_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8scluster',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k8s_clusters', to='rbac_permission.project', verbose_name='所属项目'),
        ),
    ]
