# Generated by Django 5.2 on 2026-03-11 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='环境名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='环境标识')),
            ],
            options={
                'verbose_name': '环境管理',
                'verbose_name_plural': '环境管理',
                'db_table': 'cmdb_environment',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='外网IP')),
                ('private_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP')),
                ('os_type', models.CharField(default='Linux', max_length=64, verbose_name='操作系统')),
                ('cpu', models.IntegerField(default=2, verbose_name='CPU核数')),
                ('memory', models.IntegerField(default=2, verbose_name='内存(GB)')),
                ('disk', models.IntegerField(default=20, verbose_name='磁盘(GB)')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '在线'), (2, '故障'), (3, '备用')], default=1, verbose_name='主机状态')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='host_management.environment', verbose_name='所属环境')),
            ],
            options={
                'verbose_name': '主机管理',
                'verbose_name_plural': '主机管理',
                'db_table': 'cmdb_host',
                'ordering': ['-create_time'],
            },
        ),
    ]
