# Generated by Django 5.2 on 2026-03-16 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='平台名称')),
                ('type', models.CharField(choices=[('aliyun', '阿里云 (Aliyun)'), ('tencent', '腾讯云 (Tencent)'), ('aws', '亚马逊云 (AWS)'), ('vmware', '虚拟化 (VMware)'), ('k8s', '容器集群 (Kubernetes)'), ('physical', '传统机房 (Physical)'), ('other', '其他 (Other)')], default='vmware', max_length=50, verbose_name='平台类型')),
            ],
            options={
                'verbose_name': '云平台配置',
                'verbose_name_plural': '云平台配置',
                'db_table': 'cmdb_platform',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='host_management.platform', verbose_name='所属平台'),
        ),
        migrations.CreateModel(
            name='ResourcePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='资源池名称')),
                ('code', models.CharField(help_text='只能包含英文和下划线，如: web_servers', max_length=50, unique=True, verbose_name='资源池标识(用作Ansible中Group名称)')),
                ('hosts', models.ManyToManyField(blank=True, related_name='pools', to='host_management.host', verbose_name='包含的主机')),
            ],
            options={
                'verbose_name': '资源池',
                'verbose_name_plural': '资源池',
                'db_table': 'cmdb_resource_pool',
            },
        ),
    ]
