# Generated by Django 5.2 on 2026-03-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0002_platform_host_platform_resourcepool'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ports',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='开放端口'),
        ),
    ]
