# Generated by Django 5.2 on 2026-03-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0003_host_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
