# Generated by Django 5.2 on 2026-03-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0004_platform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='access_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Key'),
        ),
        migrations.AddField(
            model_name='platform',
            name='api_endpoint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API 端点'),
        ),
        migrations.AddField(
            model_name='platform',
            name='connectivity_status',
            field=models.IntegerField(choices=[(0, '未验证'), (1, '正常'), (2, '异常')], default=0, verbose_name='连通性状态'),
        ),
        migrations.AddField(
            model_name='platform',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='platform',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次验证时间'),
        ),
        migrations.AddField(
            model_name='platform',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret Key'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平台名称'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='status',
            field=models.BooleanField(default=True, verbose_name='启用状态'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='type',
            field=models.CharField(blank=True, choices=[('aliyun', '阿里云 (Aliyun)'), ('tencent', '腾讯云 (Tencent)'), ('aws', '亚马逊云 (AWS)'), ('vmware', '虚拟化 (VMware)'), ('k8s', '容器集群 (Kubernetes)'), ('physical', '传统机房 (Physical)'), ('other', '其他 (Other)')], default='vmware', max_length=50, null=True, verbose_name='平台类型'),
        ),
    ]
