# Generated by Django 5.2 on 2026-03-17 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0005_platform_access_key_platform_api_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SshCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='凭据名称')),
                ('username', models.CharField(default='root', max_length=100, verbose_name='用户名')),
                ('auth_type', models.CharField(choices=[('password', '账号密码'), ('key', 'SSH 密钥')], default='password', max_length=20, verbose_name='认证方式')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('private_key', models.TextField(blank=True, null=True, verbose_name='私钥内容')),
                ('passphrase', models.CharField(blank=True, max_length=255, null=True, verbose_name='私钥密码')),
            ],
            options={
                'verbose_name': 'SSH 凭据',
                'verbose_name_plural': 'SSH 凭据',
                'db_table': 'cmdb_ssh_credential',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='host_management.sshcredential', verbose_name='SSH 登录凭据'),
        ),
        migrations.AddField(
            model_name='platform',
            name='default_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='host_management.sshcredential', verbose_name='平台默认 SSH 凭据'),
        ),
    ]
