# Generated by Django 5.2 on 2026-03-17 07:25

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0006_sshcredential_host_credential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshcredential',
            name='passphrase',
            field=utils.fields.EncryptedCharField(blank=True, max_length=512, null=True, verbose_name='私钥密码'),
        ),
        migrations.AlterField(
            model_name='sshcredential',
            name='password',
            field=utils.fields.EncryptedCharField(blank=True, max_length=512, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='sshcredential',
            name='private_key',
            field=utils.fields.EncryptedTextField(blank=True, null=True, verbose_name='私钥内容'),
        ),
    ]
