# Generated by Django 5.2 on 2026-05-16 04:53

import django.core.validators
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0007_alter_sshcredential_passphrase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='color',
            field=models.CharField(default='#1890ff', max_length=20, verbose_name='环境颜色'),
        ),
        migrations.AddField(
            model_name='sshcredential',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述备注'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='access_key',
            field=utils.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Access Key'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='secret_key',
            field=utils.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Secret Key'),
        ),
        migrations.AlterField(
            model_name='resourcepool',
            name='code',
            field=models.CharField(help_text='只能包含英文数字和下划线，且必须以字母开头，如: web_servers', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='资源池标识必须以字母开头，且仅能包含字母、数字和下划线。', regex='^[a-zA-Z][a-zA-Z0-9_]*$')], verbose_name='资源池标识(用作Ansible中Group名称)'),
        ),
    ]
