# Generated by Django 5.2 on 2026-05-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0008_environment_color_sshcredential_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, verbose_name='基线名称')),
                ('check_playbook', models.TextField(help_text='用于巡检主机状态的 Playbook 内容', verbose_name='检查剧本 (Ansible)')),
                ('auto_remediate', models.BooleanField(default=False, verbose_name='发现异常自动修复')),
                ('remediate_playbook', models.TextField(blank=True, help_text='当基线不通过时自动运行的 Playbook', null=True, verbose_name='修复剧本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用定期巡检')),
                ('last_check_time', models.DateTimeField(blank=True, null=True, verbose_name='最近检查时间')),
                ('resource_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='host_management.resourcepool', verbose_name='目标资源池')),
            ],
            options={
                'verbose_name': '主机基线',
                'verbose_name_plural': '主机基线',
                'db_table': 'cmdb_host_baseline',
            },
        ),
    ]
