# Generated by Django 5.2 on 2026-05-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0009_hostbaseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostbaseline',
            name='last_check_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='最近巡检状态'),
        ),
        migrations.AddField(
            model_name='hostbaseline',
            name='last_execution_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='最近执行ID'),
        ),
        migrations.AlterField(
            model_name='hostbaseline',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='hostbaseline',
            name='last_check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近巡检时间'),
        ),
    ]
