# Generated by Django 5.2 on 2026-05-25 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0010_hostbaseline_last_check_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, verbose_name='框架名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='框架标识')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='版本号')),
                ('description', models.TextField(blank=True, null=True, verbose_name='框架描述')),
            ],
            options={
                'verbose_name': '合规框架',
                'verbose_name_plural': '合规框架',
                'db_table': 'cmdb_compliance_framework',
            },
        ),
        migrations.CreateModel(
            name='ComplianceClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('code', models.CharField(max_length=50, verbose_name='条款编号')),
                ('name', models.CharField(max_length=100, verbose_name='条款名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='条款描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='host_management.complianceclause', verbose_name='上级条款')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='host_management.complianceframework', verbose_name='所属框架')),
            ],
            options={
                'verbose_name': '合规条款',
                'verbose_name_plural': '合规条款',
                'db_table': 'cmdb_compliance_clause',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceBaselineMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_mappings', to='host_management.hostbaseline', verbose_name='主机基线')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_mappings', to='host_management.complianceclause', verbose_name='合规条款')),
            ],
            options={
                'verbose_name': '条款基线映射',
                'verbose_name_plural': '条款基线映射',
                'db_table': 'cmdb_compliance_baseline_mapping',
                'unique_together': {('clause', 'baseline')},
            },
        ),
    ]
