# Generated by Django 5.2 on 2026-05-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0011_complianceframework_complianceclause_and_more'),
        ('rbac_permission', '0019_project_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='rbac_permission.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='resourcepool',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_pools', to='rbac_permission.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='sshcredential',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssh_credentials', to='rbac_permission.project', verbose_name='所属项目'),
        ),
    ]
