# Generated by Django 5.2 on 2026-06-09 09:35

import django.db.models.deletion
from django.db import migrations, models


def backfill_platform_projects(apps, schema_editor):
    Platform = apps.get_model('host_management', 'Platform')
    Project = apps.get_model('rbac_permission', 'Project')
    default_project = (
        Project.objects.filter(code='default').first()
        or Project.objects.first()
    )

    for platform in Platform.objects.filter(project__isnull=True):
        project_ids = list(
            platform.hosts.exclude(project__isnull=True)
            .values_list('project_id', flat=True)
            .distinct()[:2]
        )
        if len(project_ids) == 1:
            platform.project_id = project_ids[0]
        elif default_project:
            platform.project_id = default_project.id
        if platform.project_id:
            platform.save(update_fields=['project'])


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0012_host_project_resourcepool_project_and_more'),
        ('rbac_permission', '0021_add_project_asset_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='rbac_permission.project', verbose_name='所属项目'),
        ),
        migrations.RunPython(
            backfill_platform_projects,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=128, verbose_name='主机名'),
        ),
        migrations.AddConstraint(
            model_name='host',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'hostname'), name='uniq_host_project_hostname'),
        ),
        migrations.AddConstraint(
            model_name='host',
            constraint=models.UniqueConstraint(condition=models.Q(('private_ip__isnull', False), ('project__isnull', False)), fields=('project', 'private_ip'), name='uniq_host_project_private_ip'),
        ),
    ]
