apiVersion: v1
kind: Service
metadata:
  name: {{ include "standard-app.fullname" . }}
  labels:
    {{- include "standard-app.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "standard-app.selectorLabels" . | nindent 4 }}
