# Generated by Django 5.2 on 2026-04-17 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类标识')),
                ('label', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '配置分类',
                'verbose_name_plural': '配置分类',
                'db_table': 'config_center_category',
            },
        ),
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('key', models.CharField(max_length=100, verbose_name='配置键')),
                ('value', models.JSONField(verbose_name='配置值')),
                ('value_type', models.CharField(choices=[('string', '字符串'), ('int', '整数'), ('float', '浮点数'), ('bool', '布尔值'), ('json', 'JSON对象')], default='string', max_length=20, verbose_name='值类型')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='是否加密')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='config_center.configcategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '配置项',
                'verbose_name_plural': '配置项',
                'db_table': 'config_center_item',
                'unique_together': {('category', 'key')},
            },
        ),
    ]
