# Generated by Django 5.2 on 2026-04-17 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('rollback', '回滚')], max_length=20, verbose_name='操作类型')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='旧值')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='新值')),
                ('operator_username', models.CharField(blank=True, max_length=150, verbose_name='操作人用户名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作IP')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='变更原因')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='config_center.configitem', verbose_name='配置项')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '配置变更日志',
                'verbose_name_plural': '配置变更日志',
                'db_table': 'config_center_change_log',
                'ordering': ['-create_time'],
            },
        ),
    ]
