"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os, sys
from datetime import timedelta


env = environ.Env(
    # 设置默认值和类型
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# 新建的app不必再加apps.前缀了
# sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# 读取 .env 文件
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# 从 .env 中读取 SECRET_KEY
SECRET_KEY = env('SECRET_KEY')

# 从 .env 中读取 DEBUG
DEBUG = env('DEBUG')

# 从 .env 中读取 ALLOWED_HOSTS 并转为列表
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# 数据库配置
DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR}/db.sqlite3')
}

DATABASES['default']['CONN_MAX_AGE'] = 60

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-(&)t3&2pj^t-%kak)ym-+cqw3sw^+ce8ep@#43&i@h=i8p31@c'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne', # WebSocket
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'channels',
    'rest_framework',
    'django_celery_results',
    'django_celery_beat',
    'drf_spectacular',
    'django_filters', # 查询过滤
    'corsheaders', # 跨域
    'rest_framework_simplejwt.token_blacklist', # RT黑名单

    'apps.host_management',
    'apps.rbac_permission',
    'apps.task_management',
    'apps.k8s_management',
    'apps.pipeline_management',
    'apps.registry_management',
    'apps.system_management',
    'apps.approval_center',
    'apps.credentials_management',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 开启自定义的审计中间件
    'utils.middleware.AuditLogMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 是否启用admin后台管理
ENABLE_ADMIN = False

AUTH_USER_MODEL = 'rbac_permission.User'

REST_FRAMEWORK = {
    # 身份验证配置
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # 设置全局权限（默认所有接口都必须登录才能看）
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    # 分页配置
    'DEFAULT_PAGINATION_CLASS': 'utils.pagination.MyCustomPagination', # 指向自定义分页类
    'PAGE_SIZE': 20, # 默认每页条数

    # 过滤与搜索
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend', # 模糊/精确过滤 添加'django_filters'
        'rest_framework.filters.SearchFilter',               # 关键词搜索
        'rest_framework.filters.OrderingFilter',             # 排序
    ),

    # --- 版本控制配置 ---
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',  # 默认版本
    'ALLOWED_VERSIONS': ['v1', 'v2'],  # 允许的版本列表 Todo：需要进一步的规划
    'VERSION_PARAM': 'version',  # URL 中的参数名

    # 启用全局异常处理
    'EXCEPTION_HANDLER': 'utils.exception_handler.custom_exception_handler',

    # 启用全局响应渲染
    'DEFAULT_RENDERER_CLASSES': (
        'utils.renderers.GlobalJSONRenderer',  # 自定义渲染器
        'rest_framework.renderers.BrowsableAPIRenderer',  # 方便浏览器查看
    ),

    # 指定生成文档的类
    # 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # 使用自定义的
    'DEFAULT_SCHEMA_CLASS': 'utils.schema.RBACAutoSchema',
}


# JWT 的具体设置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 令牌有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # 刷新令牌有效期
    'AUTH_HEADER_TYPES': ('Bearer',),                # 请求头前缀：Authorization: Bearer <token>
    'ROTATE_REFRESH_TOKENS': True,  # 每次刷新 access 时，也换一个新的 refresh
    'BLACKLIST_AFTER_ROTATION': False, # 设为 True 可以让旧 Token 彻底失效
}

# 缓存设置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # 统一改为 db 0，兼容集群
        "LOCATION": "redis://127.0.0.1:6379/6",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        },
        # 增加全局前缀 ‘项目名:版本:用户id’
        # 存入 Redis 的键变成 "demo_0304:1:user_perms_1"
        "KEY_PREFIX": "ansFlow",
        "VERSION": 1, # 用于版本迭代，修改它能一次性失效所有旧缓存
    }
}

# Channels 消息层配置 (使用 Redis 做中控)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/6')],
        },
    },
}


# 设置缓存的过期时间
CACHE_TTL = 60 * 60  # 1 小时

# Celery 设置
# CELERY_BROKER_URL = 'redis://127.0.0.1:6379/6'  # 使用 Redis 做任务队列
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/6')
CELERY_RESULT_BACKEND = 'django-db'              # 将任务结果存入数据库
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# 开启扩展结果模式，数据库记录 task_name、args、kwargs 等额外信息
CELERY_RESULT_EXTENDED = True

# Spectacular 的具体配置
SPECTACULAR_SETTINGS = {
    'TITLE': 'AnsFlow 运维平台 API',
    'DESCRIPTION': '基于 Django + DRF 的自动化运维平台后端接口文档',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # 授权配置（让 Swagger 支持 JWT 在线调试）
    'COMPONENT_SPLIT_PATCH': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
    # 'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAdminUser'], # 只允许管理员看
    'SECURITY': [
        {'jwtAuth': []}
    ],
    'APPEND_COMPONENTS': {
        "securitySchemes": {
            "jwtAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
}

# 配置允许跨域的白名单 (从 .env 读取)
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:3000', # 前端开发默认地址
    'http://127.0.0.1:3000',
])

# Celery Beat 定时任务配置
CELERY_BEAT_SCHEDULE = {
    'verify-platforms-every-hour': {
        'task': 'verify_platform_connectivity',
        # 'schedule': 3600.0,  # 每小时执行一次 (单位: 秒)
        'schedule': 60,
    },
}
# 允许携带 Cookie
CORS_ALLOW_CREDENTIALS = True
# 配置 CSRF 信任域名 (用于生产环境 HTTPS)
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'http://localhost:3000',
    'http://127.0.0.1:3000',
])

# =============================================
# 统一日志配置
# =============================================
import os
import logging
from pythonjsonlogger import jsonlogger

# 日志级别（默认 INFO，可通过环境变量覆盖）
LOG_LEVEL = env('ANSFLOW_LOG_LEVEL', default='INFO').upper()

# 日志目录（默认使用项目内的 logs 目录，避免权限问题）
LOG_DIR = env('ANSFLOW_LOG_DIR', default=os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'logs'))
os.makedirs(LOG_DIR, exist_ok=True)

# 是否使用 JSON 格式
LOG_JSON = env.bool('ANSFLOW_LOG_JSON', default=True)

# 日志轮转策略：daily=按天，size=按大小
LOG_ROTATION = env('ANSFLOW_LOG_ROTATION', default='daily')

# 单个日志文件最大大小（MB），仅在 size 策略下生效
LOG_MAX_SIZE = env('ANSFLOW_LOG_MAX_SIZE', default=100, cast=int)

# 保留日志天数
LOG_RETENTION_DAYS = env('ANSFLOW_LOG_RETENTION_DAYS', default=30, cast=int)


class CustomJsonFormatter(jsonlogger.JsonFormatter):
    """自定义 JSON 格式化器，增加额外字段"""

    def add_fields(self, log_record, record, message_dict):
        super().add_fields(log_record, record, message_dict)
        log_record['service'] = 'ansflow'
        log_record['level'] = record.levelname
        log_record['logger'] = record.name
        log_record['module'] = record.module
        log_record['function'] = record.funcName
        log_record['line'] = record.lineno
        log_record['timestamp'] = self.formatTime(record, self.datefmt)


def get_formatter():
    """获取格式化器"""
    if LOG_JSON:
        return CustomJsonFormatter('%(timestamp)s %(level)s %(name)s %(message)s')
    else:
        return logging.Formatter(
            '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S'
        )


def get_file_handler(filename, level=LOG_LEVEL):
    """获取文件处理器"""
    filepath = os.path.join(LOG_DIR, filename)

    if LOG_ROTATION == 'size':
        from logging.handlers import RotatingFileHandler
        handler = RotatingFileHandler(
            filepath,
            maxBytes=LOG_MAX_SIZE * 1024 * 1024,
            backupCount=LOG_RETENTION_DAYS
        )
    else:
        from logging.handlers import TimedRotatingFileHandler
        handler = TimedRotatingFileHandler(
            filepath,
            when='midnight',
            interval=1,
            backupCount=LOG_RETENTION_DAYS
        )
        handler.suffix = '%Y%m%d'

    handler.setLevel(level)
    handler.setFormatter(get_formatter())
    return handler


def get_console_handler():
    """获取控制台处理器"""
    handler = logging.StreamHandler()
    handler.setLevel(logging.DEBUG)
    handler.setFormatter(get_formatter())
    return handler


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'json': {
            '()': lambda: CustomJsonFormatter('%(timestamp)s %(level)s %(name)s %(message)s'),
        },
        'standard': {
            'format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },

    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'json' if LOG_JSON else 'standard',
        },
        'file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler' if LOG_ROTATION == 'size' else 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'ansflow.log'),
            'maxBytes': LOG_MAX_SIZE * 1024 * 1024 if LOG_ROTATION == 'size' else None,
            'backupCount': LOG_RETENTION_DAYS if LOG_ROTATION == 'size' else None,
            'when': 'midnight' if LOG_ROTATION == 'daily' else None,
            'interval': 1 if LOG_ROTATION == 'daily' else None,
            'formatter': 'json' if LOG_JSON else 'standard',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler' if LOG_ROTATION == 'size' else 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'ansflow-error.log'),
            'maxBytes': LOG_MAX_SIZE * 1024 * 1024 if LOG_ROTATION == 'size' else None,
            'backupCount': LOG_RETENTION_DAYS if LOG_ROTATION == 'size' else None,
            'when': 'midnight' if LOG_ROTATION == 'daily' else None,
            'interval': 1 if LOG_ROTATION == 'daily' else None,
            'formatter': 'json' if LOG_JSON else 'standard',
        },
    },

    'root': {
        'level': LOG_LEVEL,
        'handlers': ['console', 'file', 'error_file'],
    },

    'loggers': {
        'django': {
            'level': env('ANSFLOW_LOG_DJANGO', default='WARNING'),
            'handlers': ['console', 'file', 'error_file'],
            'propagate': False,
        },
        'celery': {
            'level': env('ANSFLOW_LOG_CELERY', default='INFO'),
            'handlers': ['console', 'file', 'error_file'],
            'propagate': False,
        },
        'celery.task': {
            'level': env('ANSFLOW_LOG_CELERY_TASK', default='INFO'),
            'handlers': ['console', 'file', 'error_file'],
            'propagate': False,
        },
        'channels': {
            'level': env('ANSFLOW_LOG_CHANNELS', default='INFO'),
            'handlers': ['console', 'file', 'error_file'],
            'propagate': False,
        },
        'apps': {
            'level': LOG_LEVEL,
            'handlers': ['console', 'file', 'error_file'],
            'propagate': False,
        },
        'uvicorn': {
            'level': env('ANSFLOW_LOG_UVICORN', default='INFO'),
            'handlers': ['console', 'file'],
            'propagate': False,
        },
        'uvicorn.error': {
            'level': 'ERROR',
            'handlers': ['console', 'file', 'error_file'],
            'propagate': False,
        },
        'uvicorn.access': {
            'level': env('ANSFLOW_LOG_UVICORN_ACCESS', default='WARNING'),
            'handlers': ['console', 'file'],
            'propagate': False,
        },
    },
}