# Generated by Django 5.2 on 2026-03-19 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='流水线名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('graph_data', models.JSONField(default=dict, verbose_name='前端流程图数据')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'db_table': 'pipeline_template',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '运行中'), ('success', '执行成功'), ('failed', '执行失败'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pipeline_management.pipeline')),
                ('trigger_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pipeline_run_instance',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='PipelineNodeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('node_id', models.CharField(max_length=50, verbose_name='前端画布上的节点ID')),
                ('node_type', models.CharField(max_length=50, verbose_name='节点类型')),
                ('node_label', models.CharField(blank=True, max_length=100, verbose_name='节点可视化名称')),
                ('status', models.CharField(choices=[('pending', '等待前置节点完成'), ('running', '正在执行本节点'), ('success', '本节点成功'), ('failed', '本节点失败'), ('skipped', '已跳过')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, null=True, verbose_name='执行日志')),
                ('output_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='节点产出变量')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pipeline_management.pipelinerun')),
            ],
            options={
                'db_table': 'pipeline_node_run_log',
                'ordering': ['create_time'],
                'unique_together': {('run', 'node_id')},
            },
        ),
    ]
