# Generated by Django 5.2 on 2026-03-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='环境展示名称')),
                ('image', models.CharField(max_length=255, verbose_name='Docker 镜像地址')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='技术栈标签')),
                ('description', models.TextField(blank=True, null=True, verbose_name='用途描述')),
                ('status', models.CharField(default='READY', max_length=20, verbose_name='状态')),
            ],
            options={
                'db_table': 'pipeline_ci_environment',
                'ordering': ['-create_time'],
            },
        ),
    ]
