# Generated by Django 5.2 on 2026-03-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0002_cienvironment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='timeout',
            field=models.IntegerField(default=3600, verbose_name='流水线全局超时时间(秒)'),
        ),
        migrations.AddField(
            model_name='pipelinenoderun',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='单个节点的任务 ID'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='DAG 任务 ID'),
        ),
    ]
