# Generated by Django 5.2 on 2026-03-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0003_pipeline_timeout_pipelinenoderun_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinenoderun',
            name='status',
            field=models.CharField(choices=[('pending', '等待前置节点完成'), ('running', '正在执行本节点'), ('success', '本节点成功'), ('failed', '本节点失败'), ('skipped', '已跳过'), ('cancelled', '已取消')], default='pending', max_length=20),
        ),
    ]
