# Generated by Django 5.2 on 2026-03-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0004_alter_pipelinenoderun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='celery_periodic_task_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='绑定的 Celery PeriodicTask 的 ID'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='cron_expression',
            field=models.CharField(blank=True, help_text='例如: 0 2 * * *', max_length=100, null=True, verbose_name='Cron调度表达式'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='is_cron_enabled',
            field=models.BooleanField(default=False, verbose_name='是否启用定时调度'),
        ),
    ]
