# Generated by Django 5.2 on 2026-03-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0005_pipeline_celery_periodic_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinenoderun',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='已重试次数'),
        ),
    ]
