# Generated by Django 5.2 on 2026-04-20 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0006_pipelinenoderun_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='parent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_runs', to='pipeline_management.pipelinerun', verbose_name='父级 Run（重试时）'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='start_node_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='重试起始节点 ID'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='trigger_type',
            field=models.CharField(choices=[('manual', '手动触发'), ('schedule', '定时触发'), ('webhook', 'Webhook 触发'), ('retry', '重试触发')], default='manual', max_length=20, verbose_name='触发类型'),
        ),
    ]
