# Generated by Django 5.2 on 2026-04-21 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0007_add_retry_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(help_text='如: GitHub Push Trigger', max_length=100, verbose_name='Webhook 名称')),
                ('event_type', models.CharField(choices=[('push', '代码推送'), ('tag', '标签创建'), ('pull_request', 'Pull Request'), ('manual', '手动触发')], default='push', max_length=20, verbose_name='触发事件')),
                ('repository_url', models.CharField(blank=True, help_text='如: https://github.com/org/repo', max_length=512, null=True, verbose_name='仓库地址')),
                ('branch_filter', models.CharField(blank=True, help_text='留空表示所有分支，支持 glob 匹配如: main, release/*', max_length=255, null=True, verbose_name='分支过滤')),
                ('secret_key', models.CharField(blank=True, help_text='用于验证请求来源', max_length=128, null=True, verbose_name='签名密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('last_trigger_time', models.DateTimeField(blank=True, null=True, verbose_name='最近触发时间')),
                ('trigger_count', models.IntegerField(default=0, verbose_name='累计触发次数')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='pipeline_management.pipeline', verbose_name='关联流水线')),
            ],
            options={
                'verbose_name': '流水线 Webhook',
                'verbose_name_plural': '流水线 Webhook',
                'db_table': 'pipeline_webhook',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['pipeline', 'event_type'], name='pipeline_we_pipelin_5d5572_idx')],
            },
        ),
    ]
