# Generated by Django 5.2 on 2026-04-21 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0008_pipeline_webhook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('graph_data', models.JSONField(default=dict, verbose_name='版本快照数据')),
                ('name', models.CharField(max_length=100, verbose_name='版本名称（快照时）')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='版本描述（快照时）')),
                ('change_summary', models.CharField(blank=True, max_length=255, null=True, verbose_name='变更说明')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否为当前版本')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pipeline_management.pipeline', verbose_name='所属流水线')),
            ],
            options={
                'verbose_name': '流水线版本',
                'verbose_name_plural': '流水线版本',
                'db_table': 'pipeline_version',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['pipeline', '-version_number'], name='pipeline_ve_pipelin_d8019f_idx')],
                'unique_together': {('pipeline', 'version_number')},
            },
        ),
    ]
