# Generated by Django 5.2 on 2026-05-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0009_pipeline_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='trigger_type',
            field=models.CharField(choices=[('manual', '手动触发'), ('schedule', '定时触发'), ('webhook', 'Webhook 触发'), ('retry', '重试触发'), ('automation', '自动自愈触发')], default='manual', max_length=20, verbose_name='触发类型'),
        ),
    ]
