# Generated by Django 5.2 on 2026-05-16 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0010_alter_pipelinerun_trigger_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinenoderun',
            name='approval_comment',
            field=models.TextField(blank=True, null=True, verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='pipelinenoderun',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='pipelinenoderun',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pipeline_nodes', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='pipelinenoderun',
            name='status',
            field=models.CharField(choices=[('pending', '等待前置节点完成'), ('waiting', '等待人工审批'), ('running', '正在执行本节点'), ('success', '本节点成功'), ('failed', '本节点失败'), ('skipped', '已跳过'), ('cancelled', '已取消')], default='pending', max_length=20),
        ),
    ]
