# Generated by Django 5.2 on 2026-05-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0011_pipelinenoderun_approval_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='auto_kb_summary',
            field=models.BooleanField(default=False, help_text='流水线成功后，自动调用 AI 总结执行经验并存入知识库', verbose_name='成功后自动生成知识摘要'),
        ),
    ]
