# Generated by Django 5.2 on 2026-05-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0012_pipeline_auto_kb_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='extra_vars',
            field=models.JSONField(blank=True, default=dict, verbose_name='运行变量池'),
        ),
    ]
