# Generated by Django 5.2 on 2026-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0013_pipelinerun_extra_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='yaml_definition',
            field=models.TextField(blank=True, null=True, verbose_name='YAML 声明式定义'),
        ),
    ]
