# Generated by Django 5.2 on 2026-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0014_pipeline_yaml_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='graph_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='运行时的图数据快照'),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='yaml_definition',
            field=models.TextField(blank=True, null=True, verbose_name='运行时的 YAML 定义快照'),
        ),
    ]
