# Generated by Django 5.2 on 2026-05-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0015_pipelinerun_graph_data_pipelinerun_yaml_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='create_type',
            field=models.CharField(choices=[('manual', '人工区'), ('ai', 'AI草稿区')], db_index=True, default='manual', max_length=20, verbose_name='创建类型'),
        ),
    ]
