# Generated by Django 5.2 on 2026-05-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_management', '0016_pipeline_create_type'),
        ('rbac_permission', '0019_project_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='rbac_permission.project', verbose_name='所属项目'),
        ),
    ]
