# Generated by Django 5.2 on 2026-05-07 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('user_id', models.CharField(max_length=255, verbose_name='用户ID')),
                ('session_id', models.CharField(max_length=255, unique=True, verbose_name='会话ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='对话标题')),
            ],
            options={
                'verbose_name': 'AI 对话历史',
                'verbose_name_plural': 'AI 对话历史',
                'db_table': 'ai_chat_history',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=255, verbose_name='知识库名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('collection_name', models.CharField(max_length=255, unique=True, verbose_name='向量集合名称')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'db_table': 'ai_knowledge_base',
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=50, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_engine.aichathistory')),
            ],
            options={
                'verbose_name': 'AI 对话消息',
                'verbose_name_plural': 'AI 对话消息',
                'db_table': 'ai_chat_message',
            },
        ),
    ]
