# Generated by Django 5.2 on 2026-05-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichathistory',
            name='personality',
            field=models.CharField(choices=[('professional', 'Professional'), ('concise', 'Concise'), ('humorous', 'Humorous')], default='professional', max_length=50, verbose_name='助手性格'),
        ),
    ]
