# Generated by Django 5.2 on 2026-05-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_aichathistory_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichathistory',
            name='history_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('diagnose', 'Diagnose')], default='chat', max_length=20, verbose_name='会话类型'),
        ),
    ]
