# Generated by Django 5.2 on 2026-05-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_aichathistory_history_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='is_exported',
            field=models.BooleanField(default=False, verbose_name='是否已导出至知识库'),
        ),
    ]
