# Generated by Django 5.2 on 2026-05-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_aichatmessage_is_exported'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, verbose_name='模型标识 (如 gpt-4)')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('model_type', models.CharField(choices=[('llm', '分析模型 (LLM)'), ('embedding', '向量模型 (Embedding)')], max_length=20, verbose_name='模型类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'AI 模型',
                'verbose_name_plural': 'AI 模型',
                'db_table': 'ai_model',
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='供应商名称')),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama (Local)'), ('zhipu', '智谱 AI'), ('other', 'Other (OpenAI Compatible)')], max_length=20, verbose_name='供应商类型')),
                ('base_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='API 地址')),
                ('api_key', models.CharField(blank=True, max_length=512, null=True, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'AI 供应商',
                'verbose_name_plural': 'AI 供应商',
                'db_table': 'ai_provider',
            },
        ),
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('default_embedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_as_embedding', to='ai_engine.aimodel')),
                ('default_llm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_as_llm', to='ai_engine.aimodel')),
            ],
            options={
                'verbose_name': 'AI 全局配置',
                'verbose_name_plural': 'AI 全局配置',
                'db_table': 'ai_config',
            },
        ),
        migrations.AddField(
            model_name='aimodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_engine.aiprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('provider', 'name')},
        ),
    ]
