# Generated by Django 5.2 on 2026-05-11 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0005_aimodel_aiprovider_aiconfig_aimodel_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama (Local)'), ('zhipu', '智谱 AI'), ('local', 'FastEmbed (Local)'), ('other', 'Other (OpenAI Compatible)')], max_length=20, verbose_name='供应商类型'),
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('source_type', models.CharField(choices=[('manual', '手动录入'), ('file', '文件上传'), ('ai_export', 'AI 导出')], default='manual', max_length=20, verbose_name='来源类型')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ai_engine.knowledgebase', verbose_name='所属知识库')),
            ],
            options={
                'verbose_name': '知识文档',
                'verbose_name_plural': '知识文档',
                'db_table': 'ai_knowledge_document',
            },
        ),
    ]
