# Generated by Django 5.2 on 2026-05-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0006_alter_aiprovider_provider_type_knowledgedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='英文描述'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='知识库英文名称'),
        ),
    ]
