# Generated by Django 5.2 on 2026-05-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0007_knowledgebase_description_en_knowledgebase_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='chunk_count',
            field=models.IntegerField(default=0, verbose_name='切片数量'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='file_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='文件存储路径'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='status',
            field=models.CharField(choices=[('pending', '待索引'), ('processing', '处理中'), ('ready', '已就绪'), ('error', '异常')], default='ready', max_length=20, verbose_name='处理状态'),
        ),
    ]
