# Generated by Django 5.2 on 2026-05-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0008_knowledgedocument_chunk_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('content', models.TextField(verbose_name='分块内容')),
                ('vector_id', models.CharField(db_index=True, max_length=100, verbose_name='向量库ID')),
                ('index', models.IntegerField(default=0, verbose_name='序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_engine.knowledgedocument', verbose_name='所属文档')),
            ],
            options={
                'verbose_name': '知识分块',
                'verbose_name_plural': '知识分块',
                'db_table': 'ai_knowledge_chunk',
                'ordering': ['document', 'index'],
            },
        ),
    ]
