# Generated by Django 5.2 on 2026-05-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0009_knowledgechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='rag_bm25_weight',
            field=models.FloatField(default=0.3, verbose_name='关键词搜索权重'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='rag_score_threshold',
            field=models.FloatField(default=0.4, verbose_name='相似度阈值'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='rag_top_k',
            field=models.IntegerField(default=5, verbose_name='检索召回数量 (Top-K)'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='rag_vector_weight',
            field=models.FloatField(default=0.7, verbose_name='向量搜索权重'),
        ),
    ]
