# Generated by Django 5.2 on 2026-05-16 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0010_aiconfig_rag_bm25_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='default_rerank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_as_rerank', to='ai_engine.aimodel', verbose_name='默认重排序模型'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_type',
            field=models.CharField(choices=[('llm', '分析模型 (LLM)'), ('embedding', '向量模型 (Embedding)'), ('rerank', '重排序模型 (Rerank)')], max_length=20, verbose_name='模型类型'),
        ),
    ]
