# Generated by Django 5.2 on 2026-05-16 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0011_aiconfig_default_rerank_alter_aimodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='default_kb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.knowledgebase', verbose_name='默认知识库'),
        ),
    ]
