# Generated by Django 5.2 on 2026-05-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0012_aiconfig_default_kb'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='last_reindex_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近重建时间'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='reindex_error',
            field=models.TextField(blank=True, null=True, verbose_name='重建错误信息'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='reindex_status',
            field=models.CharField(choices=[('idle', '空闲'), ('processing', '重建中'), ('success', '重建成功'), ('error', '重建异常')], default='idle', max_length=20, verbose_name='重建状态'),
        ),
    ]
