# Generated by Django 5.2 on 2026-05-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0013_knowledgebase_last_reindex_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama (Local)'), ('lmstudio', 'LM Studio (Local)'), ('zhipu', '智谱 AI'), ('local', 'FastEmbed (Local)'), ('other', 'Other (OpenAI Compatible)')], max_length=20, verbose_name='供应商类型'),
        ),
    ]
