# Generated by Django 5.2 on 2026-05-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0014_alter_aiprovider_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='num_ctx',
            field=models.IntegerField(default=4096, verbose_name='上下文窗口长度 (tokens)'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件类型'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='parser_type',
            field=models.CharField(choices=[('auto', '自动识别'), ('native', '原生提取 (快速文本)'), ('ocr', 'OCR 视觉解析'), ('hybrid', '混合增强 (带图表文档)')], default='auto', max_length=20, verbose_name='解析器类型'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='parsing_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='解析提示词'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('parsing', '正在解析'), ('cleaning', '清洗中'), ('chunking', '正在切片'), ('indexing', '正在索引'), ('ready', '已就绪'), ('error', '异常')], default='ready', max_length=20, verbose_name='处理状态'),
        ),
    ]
