# Generated by Django 5.2 on 2026-05-19 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0015_aimodel_num_ctx_knowledgedocument_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='default_vision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_as_vision', to='ai_engine.aimodel', verbose_name='默认视觉/OCR模型'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, verbose_name='模型能力 (多选)'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_type',
            field=models.CharField(choices=[('llm', '分析模型 (LLM)'), ('embedding', '向量模型 (Embedding)'), ('rerank', '重排序模型 (Rerank)'), ('vision', '视觉模型 (Vision/OCR)')], max_length=20, verbose_name='主要模型类型'),
        ),
    ]
