# Generated by Django 5.2 on 2026-05-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0016_aiconfig_default_vision_aimodel_capabilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='model_type',
            field=models.CharField(blank=True, choices=[('llm', '分析模型 (LLM)'), ('embedding', '向量模型 (Embedding)'), ('rerank', '重排序模型 (Rerank)'), ('vision', '视觉模型 (Vision/OCR)')], max_length=20, verbose_name='模型类型 (自动衍生)'),
        ),
    ]
