# Generated by Django 5.2 on 2026-05-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0017_alter_aimodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='元数据'),
        ),
    ]
