# Generated by Django 5.2 on 2026-05-25 03:21

from django.db import migrations, models


def seed_prompts(apps, schema_editor):
    AIPromptTemplate = apps.get_model('ai_engine', 'AIPromptTemplate')
    from apps.ai_engine.prompt_defaults import DEFAULT_PROMPTS
    for code, info in DEFAULT_PROMPTS.items():
        AIPromptTemplate.objects.get_or_create(
            code=code,
            defaults={
                "name": info["name"],
                "template": info["template"],
                "description": info["description"],
                "is_system": True
            }
        )

def clear_prompts(apps, schema_editor):
    AIPromptTemplate = apps.get_model('ai_engine', 'AIPromptTemplate')
    AIPromptTemplate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0018_aichatmessage_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='模板代码')),
                ('template', models.TextField(verbose_name='模板内容')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模板描述')),
                ('is_system', models.BooleanField(default=True, verbose_name='是否系统内置')),
            ],
            options={
                'verbose_name': 'AI 提示词模板',
                'verbose_name_plural': 'AI 提示词模板',
                'db_table': 'ai_prompt_template',
            },
        ),
        migrations.RunPython(seed_prompts, reverse_code=clear_prompts),
    ]
