# Generated by Django 5.2 on 2026-05-08 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline_management', '0009_pipeline_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('alert_name', models.CharField(max_length=255, verbose_name='告警名称')),
                ('severity', models.CharField(max_length=50, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('firing', '告警中'), ('resolved', '已恢复')], default='firing', max_length=20)),
                ('source', models.CharField(choices=[('prometheus', 'Prometheus'), ('zabbix', 'Zabbix'), ('aliyun', 'Aliyun CloudMonitor'), ('other', 'Other')], default='prometheus', max_length=50)),
                ('fingerprint', models.CharField(db_index=True, max_length=128, verbose_name='告警指纹')),
                ('labels', models.JSONField(default=dict, verbose_name='告警标签')),
                ('annotations', models.JSONField(default=dict, verbose_name='告警注释')),
                ('healing_status', models.CharField(choices=[('none', '未处理'), ('analyzing', 'AI 分析中'), ('suggested', '已有建议'), ('executing', '自愈中'), ('success', '自愈成功'), ('failed', '自愈失败'), ('ignored', '已忽略')], default='none', max_length=20)),
                ('ai_analysis', models.TextField(blank=True, null=True, verbose_name='AI 分析结论')),
                ('suggested_pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline_management.pipeline', verbose_name='建议自愈流水线')),
            ],
            options={
                'verbose_name': '告警事件',
                'verbose_name_plural': '告警事件',
                'db_table': 'sre_alert_event',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SelfHealingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('alert_match_rule', models.JSONField(help_text="例如: {'alertname': 'CPUUsageTooHigh'}", verbose_name='告警匹配规则')),
                ('is_auto_execute', models.BooleanField(default=False, help_text='开启后无需审批自动触发流水线', verbose_name='是否自动执行')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline_management.pipeline', verbose_name='关联自愈流水线')),
            ],
            options={
                'verbose_name': '自愈策略',
                'verbose_name_plural': '自愈策略',
                'db_table': 'sre_healing_policy',
            },
        ),
    ]
