# Generated by Django 5.2 on 2026-05-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='is_exported',
            field=models.BooleanField(default=False, verbose_name='是否已导出至知识库'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='latest_run_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='最近一次运行ID'),
        ),
    ]
