# Generated by Django 5.2 on 2026-05-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre_management', '0002_alertevent_is_exported_alertevent_latest_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='trigger_type',
            field=models.CharField(blank=True, choices=[('manual', '手动'), ('auto', '自动')], max_length=20, null=True, verbose_name='触发类型'),
        ),
    ]
