# Generated by Django 5.2 on 2026-05-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre_management', '0003_alertevent_trigger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='matched_policy_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='匹配到的策略名称'),
        ),
    ]
