# Generated by Django 5.2 on 2026-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre_management', '0004_alertevent_matched_policy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='latest_ticket_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='最近一次审批工单ID'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='healing_status',
            field=models.CharField(choices=[('none', '未处理'), ('analyzing', 'AI 分析中'), ('suggested', '已有建议'), ('awaiting_approval', '待审批'), ('executing', '自愈中'), ('success', '自愈成功'), ('failed', '自愈失败'), ('ignored', '已忽略')], default='none', max_length=20),
        ),
    ]
