# Generated by Django 5.2 on 2026-05-26 06:31

import django.db.models.deletion
from django.db import migrations, models


def set_default_project(apps, schema_editor):
    SelfHealingPolicy = apps.get_model('sre_management', 'SelfHealingPolicy')
    Project = apps.get_model('rbac_permission', 'Project')
    default_project = Project.objects.filter(code='default').first()
    if default_project:
        SelfHealingPolicy.objects.filter(project__isnull=True).update(project=default_project)

class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0020_initialize_default_project'),
        ('sre_management', '0005_alertevent_latest_ticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfhealingpolicy',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='是否为全局兜底策略'),
        ),
        migrations.AddField(
            model_name='selfhealingpolicy',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_healing_policies', to='rbac_permission.project', verbose_name='所属项目'),
        ),
        migrations.RunPython(set_default_project, reverse_code=migrations.RunPython.noop),
    ]
