# Generated by Django 5.2 on 2026-06-02 09:40

import django.db.models.deletion
import utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0012_host_project_resourcepool_project_and_more'),
        ('k8s_management', '0006_k8scluster_project'),
        ('rbac_permission', '0021_add_project_asset_share'),
        ('sre_management', '0006_selfhealingpolicy_is_global_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservabilityDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='数据源名称')),
                ('type', models.CharField(choices=[('victoriametrics', 'VictoriaMetrics'), ('victorialogs', 'VictoriaLogs')], max_length=30, verbose_name='数据源类型')),
                ('base_url', models.URLField(max_length=500, verbose_name='访问地址')),
                ('auth_type', models.CharField(choices=[('none', '无认证'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth')], default='none', max_length=20, verbose_name='认证方式')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名')),
                ('password', utils.fields.EncryptedCharField(blank=True, max_length=512, null=True, verbose_name='密码')),
                ('token', utils.fields.EncryptedTextField(blank=True, null=True, verbose_name='Token')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, verbose_name='请求超时秒数')),
            ],
            options={
                'verbose_name': '观测数据源',
                'verbose_name_plural': '观测数据源',
                'db_table': 'sre_observability_datasource',
                'ordering': ['-is_default', '-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='source',
            field=models.CharField(choices=[('prometheus', 'Prometheus'), ('vmalert', 'VictoriaMetrics vmalert'), ('victoriametrics', 'VictoriaMetrics'), ('zabbix', 'Zabbix'), ('aliyun', 'Aliyun CloudMonitor'), ('other', 'Other')], default='prometheus', max_length=50),
        ),
        migrations.CreateModel(
            name='ObservedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('code', models.CharField(max_length=80, verbose_name='服务标识')),
                ('namespace', models.CharField(blank=True, max_length=120, null=True, verbose_name='K8s 命名空间')),
                ('metric_label_selector', models.JSONField(blank=True, default=dict, verbose_name='指标标签选择器')),
                ('log_label_selector', models.JSONField(blank=True, default=dict, verbose_name='日志标签选择器')),
                ('metric_queries', models.JSONField(blank=True, default=list, verbose_name='自定义指标查询')),
                ('log_query', models.TextField(blank=True, null=True, verbose_name='自定义日志查询')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observed_services', to='host_management.environment', verbose_name='环境')),
                ('hosts', models.ManyToManyField(blank=True, related_name='observed_services', to='host_management.host', verbose_name='关联主机')),
                ('k8s_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observed_services', to='k8s_management.k8scluster', verbose_name='K8s 集群')),
                ('log_datasource', models.ForeignKey(blank=True, limit_choices_to={'type': 'victorialogs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_services', to='sre_management.observabilitydatasource', verbose_name='日志数据源')),
                ('metric_datasource', models.ForeignKey(blank=True, limit_choices_to={'type': 'victoriametrics'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_services', to='sre_management.observabilitydatasource', verbose_name='指标数据源')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observed_services', to='rbac_permission.project', verbose_name='所属项目')),
                ('resource_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observed_services', to='host_management.resourcepool', verbose_name='资源池')),
            ],
            options={
                'verbose_name': '可观测服务',
                'verbose_name_plural': '可观测服务',
                'db_table': 'sre_observed_service',
                'ordering': ['project__name', 'name'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DiagnosisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('title', models.CharField(max_length=200, verbose_name='诊断标题')),
                ('trigger_type', models.CharField(choices=[('manual', '手动'), ('alert', '告警'), ('retry', '重试')], default='manual', max_length=20, verbose_name='触发方式')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('diagnosis_time', models.DateTimeField(verbose_name='诊断时间点')),
                ('window_minutes', models.PositiveIntegerField(default=10, verbose_name='前后窗口分钟数')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='查询参数')),
                ('context_snapshot', models.JSONField(blank=True, default=dict, verbose_name='诊断上下文')),
                ('ai_result', models.TextField(blank=True, null=True, verbose_name='AI 诊断结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_runs', to='sre_management.alertevent', verbose_name='关联告警')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_runs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_runs', to='rbac_permission.project', verbose_name='项目')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_runs', to='sre_management.observedservice', verbose_name='服务')),
            ],
            options={
                'verbose_name': '时间点诊断',
                'verbose_name_plural': '时间点诊断',
                'db_table': 'sre_diagnosis_run',
                'ordering': ['-create_time'],
            },
        ),
    ]
