# Generated by Django 5.2 on 2026-06-03 02:34

import django.db.models.deletion
from django.db import migrations, models


def sync_datasource_kind_and_provider(apps, schema_editor):
    ObservabilityDataSource = apps.get_model('sre_management', 'ObservabilityDataSource')
    log_providers = {'victorialogs', 'elasticsearch', 'loki', 'aliyun_sls', 'tencent_cls', 'generic_http'}
    for datasource in ObservabilityDataSource.objects.all():
        datasource.provider = datasource.type
        datasource.kind = 'log' if datasource.type in log_providers else 'metric'
        datasource.save(update_fields=['provider', 'kind'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sre_management', '0007_observabilitydatasource_alter_alertevent_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observabilitydatasource',
            name='field_mapping',
            field=models.JSONField(blank=True, default=dict, verbose_name='字段映射'),
        ),
        migrations.AddField(
            model_name='observabilitydatasource',
            name='kind',
            field=models.CharField(choices=[('metric', '指标'), ('log', '日志'), ('trace', '链路追踪')], default='metric', max_length=20, verbose_name='数据类别'),
        ),
        migrations.AddField(
            model_name='observabilitydatasource',
            name='provider',
            field=models.CharField(choices=[('victoriametrics', 'VictoriaMetrics'), ('victorialogs', 'VictoriaLogs'), ('elasticsearch', 'Elasticsearch'), ('loki', 'Loki'), ('aliyun_sls', '阿里云 SLS'), ('tencent_cls', '腾讯云 CLS'), ('generic_http', '通用 HTTP')], default='victoriametrics', max_length=30, verbose_name='数据源提供方'),
        ),
        migrations.AddField(
            model_name='observabilitydatasource',
            name='query_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='查询配置'),
        ),
        migrations.AddField(
            model_name='observabilitydatasource',
            name='response_mapping',
            field=models.JSONField(blank=True, default=dict, verbose_name='响应映射'),
        ),
        migrations.RunPython(sync_datasource_kind_and_provider, noop_reverse),
        migrations.AlterField(
            model_name='observabilitydatasource',
            name='auth_type',
            field=models.CharField(choices=[('none', '无认证'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('header', '自定义请求头'), ('query', '查询参数'), ('cloud_signature', '云厂商签名')], default='none', max_length=20, verbose_name='认证方式'),
        ),
        migrations.AlterField(
            model_name='observabilitydatasource',
            name='type',
            field=models.CharField(choices=[('victoriametrics', 'VictoriaMetrics'), ('victorialogs', 'VictoriaLogs'), ('elasticsearch', 'Elasticsearch'), ('loki', 'Loki'), ('aliyun_sls', '阿里云 SLS'), ('tencent_cls', '腾讯云 CLS'), ('generic_http', '通用 HTTP')], max_length=30, verbose_name='数据源类型'),
        ),
        migrations.AlterField(
            model_name='observedservice',
            name='log_datasource',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'log'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_services', to='sre_management.observabilitydatasource', verbose_name='日志数据源'),
        ),
        migrations.AlterField(
            model_name='observedservice',
            name='metric_datasource',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'metric'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_services', to='sre_management.observabilitydatasource', verbose_name='指标数据源'),
        ),
    ]
