# Generated by Django 5.2 on 2026-03-12 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='菜单标题')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Antd菜单Key')),
                ('path', models.CharField(max_length=200, verbose_name='路由路径')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac_permission.menu', verbose_name='父级菜单')),
            ],
            options={
                'db_table': 'rbac_permission_menu',
            },
        ),
    ]
