# Generated by Django 5.2 on 2026-03-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(blank=True, to='rbac_permission.menu', verbose_name='拥有的菜单'),
        ),
    ]
