# Generated by Django 5.2 on 2026-03-12 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0003_role_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='用户名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作IP')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('resource', models.CharField(blank=True, max_length=100, verbose_name='操作资源')),
                ('action', models.CharField(blank=True, max_length=50, verbose_name='操作动作')),
                ('request_data', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('response_status', models.IntegerField(verbose_name='响应状态码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'db_table': 'rbac_audit_log',
                'ordering': ['-create_time'],
            },
        ),
    ]
