# Generated by Django 5.2 on 2026-03-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
