# Generated by Django 5.2 on 2026-03-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0005_alter_permission_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='角色标识'),
        ),
    ]
