# Generated by Django 5.2 on 2026-03-13 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0006_role_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='code',
        ),
    ]
