# Generated by Django 5.2 on 2026-03-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0008_role_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='角色标识'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='rbac_permission.permission'),
        ),
    ]
