# Generated by Django 5.2 on 2026-03-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0009_alter_role_code_alter_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('resource_type', models.CharField(choices=[('pipeline', '流水线'), ('k8s_cluster', 'K8s集群'), ('ansible_task', 'Ansible任务'), ('resource_pool', '资源池')], max_length=50)),
                ('authorized_ids', models.JSONField(default=list, verbose_name='授权的资源ID列表')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_policies', to='rbac_permission.role')),
            ],
            options={
                'db_table': 'rbac_data_policy',
                'unique_together': {('role', 'resource_type')},
            },
        ),
    ]
