# Generated by Django 5.2 on 2026-03-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0010_datapolicy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datapolicy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='datapolicy',
            name='action_type',
            field=models.CharField(choices=[('manage', '管理权限'), ('use', '引用权限')], default='manage', max_length=50, verbose_name='动作权限类型'),
        ),
        migrations.AlterUniqueTogether(
            name='datapolicy',
            unique_together={('role', 'resource_type', 'action_type')},
        ),
    ]
