# Generated by Django 5.2 on 2026-03-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0011_alter_datapolicy_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapolicy',
            name='resource_type',
            field=models.CharField(choices=[('pipeline', '流水线'), ('k8s_cluster', 'K8s集群'), ('ansible_task', 'Ansible任务'), ('resource_pool', '资源池'), ('registry', '镜像仓库'), ('credential', 'SSH 凭据')], max_length=50),
        ),
    ]
