# Generated by Django 5.2 on 2026-03-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0012_alter_datapolicy_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='danger_level',
            field=models.CharField(choices=[('safe', '安全 (只读)'), ('warn', '警告 (写/创建)'), ('high', '危险 (删除/强制操作)')], default='safe', max_length=10, verbose_name='危险等级'),
        ),
    ]
