# Generated by Django 5.2 on 2026-03-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0013_permission_danger_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='动作名称'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='duration',
            field=models.FloatField(default=0.0, verbose_name='耗时(s)'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='操作对象ID'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='资源名称'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='response_data',
            field=models.JSONField(blank=True, null=True, verbose_name='响应简报'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_data',
            field=models.JSONField(blank=True, null=True, verbose_name='请求报文'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource',
            field=models.CharField(blank=True, max_length=100, verbose_name='资源Code'),
        ),
    ]
