# Generated by Django 5.2 on 2026-03-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0014_auditlog_action_name_auditlog_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='old_data',
            field=models.JSONField(blank=True, null=True, verbose_name='修改前旧主数据的快照'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='动作名称'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='操作对象ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_data',
            field=models.JSONField(blank=True, null=True, verbose_name='请求报文(新数据)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='response_data',
            field=models.JSONField(blank=True, null=True, verbose_name='失败响应简报'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='response_status',
            field=models.IntegerField(verbose_name='HTTP状态码'),
        ),
    ]
