# Generated by Django 5.2 on 2026-04-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0015_auditlog_old_data_alter_auditlog_action_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='菜单英文标题'),
        ),
        migrations.AddField(
            model_name='menu',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
