# Generated by Django 5.2 on 2026-04-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0017_add_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='GitHub ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='ldap_dn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LDAP DN'),
        ),
        migrations.AddField(
            model_name='user',
            name='ldap_uid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='LDAP UID'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('password', '密码登录'), ('ldap', 'LDAP 登录'), ('github', 'GitHub 授权'), ('wechat', '微信授权')], default='password', max_length=20, verbose_name='登录方式'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信 OpenID'),
        ),
    ]
