# Generated by Django 5.2 on 2026-05-26 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_permission', '0020_initialize_default_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssetShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('asset_type', models.CharField(choices=[('host', 'Host 主机'), ('ssh_credential', 'SSH 凭证'), ('credential', '通用凭据'), ('pipeline', '流水线模板'), ('ansible_task', 'Ansible 任务'), ('k8s_cluster', 'K8s 集群'), ('resource_pool', '资源池'), ('self_healing_policy', '自愈策略')], max_length=50, verbose_name='资产类型')),
                ('asset_id', models.IntegerField(verbose_name='资产 ID（对应各 app 的主键）')),
                ('permission', models.CharField(choices=[('read', '只读 (read)'), ('use', '可执行 (use)'), ('full', '完全控制 (full)')], default='use', max_length=20, verbose_name='授权权限级别')),
                ('from_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_out', to='rbac_permission.project', verbose_name='来源项目（授权方）')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_shares_created', to=settings.AUTH_USER_MODEL, verbose_name='授权操作人')),
                ('to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_in', to='rbac_permission.project', verbose_name='目标项目（被授权方）')),
            ],
            options={
                'verbose_name': '跨项目资产授权',
                'verbose_name_plural': '跨项目资产授权',
                'db_table': 'rbac_project_asset_share',
                'ordering': ['-create_time'],
                'unique_together': {('from_project', 'to_project', 'asset_type', 'asset_id')},
            },
        ),
    ]
